# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163e8b1267fccc61160db3aade0b9187c0256edff7c6bb5b633386f450e0f4573a60f955ae91b29a5071ccea8a7b6e455b0abd0c24d3e87fd53062202bd8d82a

test:
  secret_key_base: 0f6c1cf525c3e258437b1926e6fe12ee2b78c853a528fad00b5d00e921f651fbaa199679cfe2560342477f6769139c0f514b078531e21e15232a9cf1b06c204c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
